# NumPy

* Third party package for scientific computing
* Operating with numbers and maths
* Use them like the usual C arrays
* Base for most processing elements like Pandas
* Less memory intensive compared to list

# NumPy Datatypes
* Integers - numpy.int8, numpy.int16, <b>numpy.int32</b>#defult,numpy.int64

* Floating point - numpy.float32,<b>numpy.float64</b>,numpy.float128
* Boolean
* Strings - Length needs to be specified in advance

In [1]:
import numpy as np

In [3]:
import numpy as np
print(np.__version__)

1.14.2


## Creating a numpy arrays

In [3]:
a=np.array([1,2,3,4,5]) #to convert a sequence to array
a

array([1, 2, 3, 4, 5])

In [4]:
a=np.array([1,2.5,3,4,5]) 
a

array([1. , 2.5, 3. , 4. , 5. ])

In [4]:
a=np.array([1,2.5,3,4,5]) 
newStrArray=a.astype(int)#type conversion
newStrArray

array([1, 2, 3, 4, 5])

In [6]:
help(a.astype)

Help on built-in function astype:

astype(...)
    a.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)
    
    Copy of the array, cast to a specified type.
    
    Parameters
    ----------
    dtype : str or dtype
        Typecode or data-type to which the array is cast.
    order : {'C', 'F', 'A', 'K'}, optional
        Controls the memory layout order of the result.
        'C' means C order, 'F' means Fortran order, 'A'
        means 'F' order if all the arrays are Fortran contiguous,
        'C' order otherwise, and 'K' means as close to the
        order the array elements appear in memory as possible.
        Default is 'K'.
    casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
        Controls what kind of data casting may occur. Defaults to 'unsafe'
        for backwards compatibility.
    
          * 'no' means the data types should not be cast at all.
          * 'equiv' means only byte-order changes are allowed.
          * 'safe' means o

In [5]:
newStrArray.tolist()#convert to python list

[1, 2, 3, 4, 5]

In [13]:
a=np.array([1,2,3,4,5,6],dtype=np.float64) #providing datatype
a

array([1., 2., 3., 4., 5., 6.])

In [14]:
print (a.ndim) #dimension of row and coloum ,
print (a.shape)
print (a.size)#no of elements

1
(6,)
6


In [15]:
a = np.array(range(1,50),dtype=np.int32)
a
a.ndim,a.shape,a.size

(1, (49,), 49)

In [ ]:
# Create a 1-D numpy array of 50 elements and display its contents
# Write a function meta that prints the dimension, shape and size of a numpy array

In [6]:
a = np.array(range(1,51))
print a
print a.ndim
print a.shape
print a.size

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
1
(50L,)
50


In [7]:
def ssd(a):
    print("dimension :"+str( a.ndim))
    print ("shape :" +str(a.shape))
    print ("size : " +str(a.size))
ssd(a)    

dimension :1
shape :(50L,)
size : 50


* Size of a numpy array is fixed
* Always recommended to create numpy arrays of same data type
* #### Uncertain about datatypes??? Use "object" datatype ####

In [16]:
sample=np.array([1,"Ram",98.2])
sample

array(['1', 'Ram', '98.2'], dtype='<U11')

In [17]:
sample=np.array([1,"Ram",98.2],dtype=np.object)#other datatype are do not affect other data type
sample

array([1, 'Ram', 98.2], dtype=object)

### Can handle Vectorized operations

In [3]:
l=[1,2,3,4]
npa=np.array(l)
l,npa

([1, 2, 3, 4], array([1, 2, 3, 4]))

In [6]:
l+2

TypeError: can only concatenate list (not "int") to list

In [21]:
npa+2 #adding a value to numpy arary

array([3, 4, 5, 6])

In [25]:
# Create an array displaying the ages of 10 students
ageList=np.array(range(10))
# Add 1 to the age values for every year and display all the ages
for year in range(2010,2020+1):
    ## your code
    ageList += 1
    print str(year)+" : "+str(ageList)
ageList    

2010 : [ 1  2  3  4  5  6  7  8  9 10]
2011 : [ 2  3  4  5  6  7  8  9 10 11]
2012 : [ 3  4  5  6  7  8  9 10 11 12]
2013 : [ 4  5  6  7  8  9 10 11 12 13]
2014 : [ 5  6  7  8  9 10 11 12 13 14]
2015 : [ 6  7  8  9 10 11 12 13 14 15]
2016 : [ 7  8  9 10 11 12 13 14 15 16]
2017 : [ 8  9 10 11 12 13 14 15 16 17]
2018 : [ 9 10 11 12 13 14 15 16 17 18]
2019 : [10 11 12 13 14 15 16 17 18 19]
2020 : [11 12 13 14 15 16 17 18 19 20]


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [26]:
import csv
# Read the weather1week.csv file
# Convert the temperature from Centigrade to Faranheit
# F=C*(9/5)+32
filename = "C:\Users\Sureya\Desktop\data analiyics\done by me on class\dataset\weather1week.csv"
with open(filename,'r') as f :
    datareader = csv.reader(f,delimiter=';')
    
    print "content"
    for i in datareader:
        c = float(i[5])
        f = (c*(9/5)+32)
        print str(f)

content
54.64
54.42
54.29
54.2
54.14
54.2
55.39
56.42
56.7
56.59
56.14
55.95
55.91
55.28
55.27
57.42
57.75
56.18
55.48
54.94
54.49
54.11
54.09
54.06
54.04
54.01
54.0
54.0
54.01
54.04
53.49
56.08
57.7
58.35
58.92
57.27
56.69
57.48
56.04
55.96
55.71
55.11
54.72
54.6
54.5
54.36
54.23
54.04
53.89
53.76
53.68
53.66
53.62
53.6
53.62
55.93
57.27
58.47
59.58
58.95
58.46
57.56
56.61
56.11
55.76
55.72
55.12
54.96
54.86
54.7
54.75
54.77
54.61
54.45
54.49
54.54
54.32
54.15
54.65
57.13
58.53
58.21
58.39
60.31
59.53
60.44
61.24
60.24
59.92
59.17
57.21
56.13
55.44
55.18
55.2
55.22
55.42
55.59
55.83
55.47
55.19
54.27
53.75
55.57
55.69
56.86
58.51
60.23
59.74
59.4
58.94
58.59
58.36
58.54
57.11
56.04
55.5
55.4
55.51
55.6
55.54
55.3
55.05
54.88
54.69
54.5
54.56
56.74
58.03
59.24
60.38
61.27
61.96
61.91
60.16
59.18
57.87
57.01
55.55
54.91
54.57
54.55
54.57
54.36
54.51
53.78
53.46
53.37
52.81
52.55
53.45
56.78
58.46
59.8
60.92
60.52
59.96
59.4
58.9
58.44
57.58
56.89
55.71
55.28
55.05
54.74
54.6
54.45
54.33

### Multi-Dimensional Arrays

In [22]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [23]:
b.ndim, b.shape, b.size, b.dtype Alliswell123$

(2, (2, 5), 10, dtype('int32'))

In [29]:
# Create a 3-D numpy array of 3X5X4 and display its contents
# Will your meta function work for this new array? Else create a new meta function
#a = np.array([[range(5)],[range(5)],[range(5)]][[range(5)],[range(5)],[range(5)]][[range(5)],[range(5)],[range(5)]][[range(5)],[range(5)],[range(5)]][[range(5)],[range(5)],[range(5)]])
#a
a = np.array([[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]])

print a,ssd(a)
#print str(a[0][0][0])

[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]] dimension :3
shape :(4L, 3L, 5L)
size : 60
None


### Some helpful functions

In [24]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
help(np.zeros)

Help on built-in function zeros in module numpy.core.multiarray:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled wi

In [30]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
# Create an Identity Matrix of size 3X3 
# Create the base using np.zeros 
a = np.zeros((3,3))
for i in range(0,3):
    for j in range(0,3):
        if i == j :
            a[i][j] = 1
#a  
for i in range(0,3):
    for j in range(0,3):
        print i,j

0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2


#### TODO ####
* WHAT IS THE DIFFERENCE BETWEEN np.zeros AND np.empty

### Sequence Generators

In [32]:
start=0
end=10
count=5
np.linspace(start,end,count)#Return evenly spaced numbers over a specified interval.
                            #Returns num evenly spaced samples, calculated over the interval [start, stop].
                            #The endpoint of the interval can optionally be excluded.

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [36]:
help(np.linspace(start,end))

Help on ndarray object:

class ndarray(__builtin__.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any ob

In [37]:
start=0
end=10
step=2
np.arange(start,end,step)#Return evenly spaced values within a given interval.

array([0, 2, 4, 6, 8])

In [38]:
np.random.standard_normal((2,4))#(mean,deviation)

array([[-0.02488551, -1.28870575,  0.65112917,  0.71750091],
       [-1.25882023,  0.35476668,  2.93147846,  1.85277343]])

In [40]:
a=np.random.standard_normal((2,3))
b=np.random.standard_normal((2,3))
a,b

(array([[-0.39937065,  1.31939252, -0.30701888],
        [-0.61753021, -0.41492012, -0.26769014]]),
 array([[ 0.68638658,  0.86552373,  0.27793809],
        [ 0.52215398, -0.79736577,  0.29622184]]))

In [41]:
np.vstack([a,b])#Stack arrays in sequence horizontally (column wise).

array([[-0.39937065,  1.31939252, -0.30701888],
       [-0.61753021, -0.41492012, -0.26769014],
       [ 0.68638658,  0.86552373,  0.27793809],
       [ 0.52215398, -0.79736577,  0.29622184]])

In [42]:
np.hstack([a,b])#Stack arrays in sequence vertically (row wise).

array([[-0.39937065,  1.31939252, -0.30701888,  0.68638658,  0.86552373,
         0.27793809],
       [-0.61753021, -0.41492012, -0.26769014,  0.52215398, -0.79736577,
         0.29622184]])

In [ ]:
a.transpose()

In [ ]:
np.save('myFirstArray.npy',a)#to save the numpy to avoid preprocessing

In [ ]:
al=np.load('myFirstArray.npy')#to 
al

In [43]:
a=[[1,2],[5,6]]
b=[[1,0],[0,1]]
np.dot(a,b)

array([[1, 2],
       [5, 6]])

In [59]:
row = input("Enter the number of rows")
col = input("Enter the number of columns")
aw = np.zeros((row,col))
for i in range(0,row):
    for i in range(0,col):
        aw[i][j] = int(input("Enter elt"))
        
print aw

Enter the number of rows3
Enter the number of columns3
Enter elt1
Enter elt2
Enter elt3
Enter elt4
Enter elt5
Enter elt6
Enter elt7
Enter elt8
Enter elt9
[[0. 0. 7.]
 [0. 0. 8.]
 [0. 0. 9.]]


## Input a matrix from user and show its properties using meta function -x- Input row, col and each elt as user input
# Transpose it and show its properties
row = int(input("Enter the row size"))
col = int(input("Enter the col size"))
a = np.zeros((row,col))

print ("Enter the no of elements "+ str(row * col))
for i in range(0,row):
    for j in range(0,col):
        a[i][j] = int (input("value of  " +str( i)+str(j) ) )
        
a    
ssd(a)
b = a.transpose()
print ("after tranpose")
ssd(b)

In [57]:
def createarray():
    row = int(input("Enter the row size"))
    col = int(input("Enter the col size"))
    a = np.zeros((row,col))

    print ("Enter the no of elements "+ str(row * col))
    for i in range(0,row):
        for j in range(0,col):
            a[i][j] = int (input("value of  " +str( i)+str(j)+":-" ) )
    print a

createarray()


Enter the row size3
Enter the col size3
Enter the no of elements 9
value of  00:-1
value of  01:-2
value of  02:-3
value of  10:-4
value of  11:-5
value of  12:-6
value of  20:-7
value of  21:-8
value of  22:-9
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# Add two 3X4 matrices
# Input two matrices from a user and find if they can be multiplied
# If yes multiply them and show the result

In [ ]:
a=np.array([range(5),range(5,10),range(10,15),range(15,20)])
b=np.array([range(4),range(4,8),range(8,12),range(12,16),range(16,20)])

# Validate the following 
# ((a)T)T = a
# (a)T+(b)T=(a+b)T
# [ab]T=(b)T(a)T

## Indexing and Slicing

In [61]:
v=np.linspace(0,10,5)
v

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [17]:
v[0],v[1],v[-1]

(0.0, 2.5, 10.0)

In [18]:
v[2:4]#python is right exclusive

array([ 5. ,  7.5])

In [19]:
vv=np.random.random((5,4))
vv

array([[ 0.60037124,  0.468652  ,  0.96245362,  0.95503114],
       [ 0.47266201,  0.80493409,  0.89137844,  0.9278601 ],
       [ 0.36682163,  0.22164909,  0.63284242,  0.92058815],
       [ 0.64664692,  0.58430721,  0.2091121 ,  0.08772873],
       [ 0.36027446,  0.3740544 ,  0.04575984,  0.42272688]])

In [20]:
vv[0,0],vv[4,3]

(0.60037124333359171, 0.42272687660470332)

In [21]:
ll=[[1,2,3],[4,5,6]]
ll[0][1]

2

In [22]:
vv

array([[ 0.60037124,  0.468652  ,  0.96245362,  0.95503114],
       [ 0.47266201,  0.80493409,  0.89137844,  0.9278601 ],
       [ 0.36682163,  0.22164909,  0.63284242,  0.92058815],
       [ 0.64664692,  0.58430721,  0.2091121 ,  0.08772873],
       [ 0.36027446,  0.3740544 ,  0.04575984,  0.42272688]])

In [23]:
vv[2:5, 1]

array([ 0.22164909,  0.58430721,  0.3740544 ])

In [24]:
vv[2:5, 0:3]#dddddddddddddddddddddd

array([[ 0.36682163,  0.22164909,  0.63284242],
       [ 0.64664692,  0.58430721,  0.2091121 ],
       [ 0.36027446,  0.3740544 ,  0.04575984]])

### Copying numpy objects

In [62]:
print v
v2=v[2:4]
print v2
v2[0]=55
print v,v2
#it is shallow copy ie it will be reflected to all the array

[ 0.   2.5  5.   7.5 10. ]
[5.  7.5]
[ 0.   2.5 55.   7.5 10. ] [55.   7.5]


In [63]:
print v
v2=v[2:4].copy()
print v2
v2[0]=100
print v,v2
#it is deep copy ie it will not  be reflected to all the ar

[ 0.   2.5 55.   7.5 10. ]
[55.   7.5]
[ 0.   2.5 55.   7.5 10. ] [100.    7.5]


### Filtering Data

In [25]:
print v
v1=v[[1,2,3]]
print v1

[  0.    2.5   5.    7.5  10. ]
[ 2.5  5.   7.5]


In [26]:
v>0

array([False,  True,  True,  True,  True], dtype=bool)

In [64]:
bool_ind=v>5

In [65]:
v[bool_ind]

array([55. ,  7.5, 10. ])

In [29]:
print vv
vv[vv>.5]

[[ 0.60037124  0.468652    0.96245362  0.95503114]
 [ 0.47266201  0.80493409  0.89137844  0.9278601 ]
 [ 0.36682163  0.22164909  0.63284242  0.92058815]
 [ 0.64664692  0.58430721  0.2091121   0.08772873]
 [ 0.36027446  0.3740544   0.04575984  0.42272688]]


array([ 0.60037124,  0.96245362,  0.95503114,  0.80493409,  0.89137844,
        0.9278601 ,  0.63284242,  0.92058815,  0.64664692,  0.58430721])

In [30]:
vv[vv>.5]=1
vv

array([[ 1.        ,  0.468652  ,  1.        ,  1.        ],
       [ 0.47266201,  1.        ,  1.        ,  1.        ],
       [ 0.36682163,  0.22164909,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  0.2091121 ,  0.08772873],
       [ 0.36027446,  0.3740544 ,  0.04575984,  0.42272688]])

In [33]:
vals=np.arange(10)
print vals
#val = np.array(1,2,3,4,5,5)
np.where(vals%3==0)#retun a index 

[0 1 2 3 4 5 6 7 8 9]


(array([0, 3, 6, 9], dtype=int64),)

In [34]:
vals_new=np.where(vals%2==0,-1,vals)
vals_new

array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9])

In [70]:
# Exercise

data=np.array([range(5),range(5,10),range(10,15),range(15,20)])
print data
vi = data[data%2==0]
print vi
#print data[data%2==0,-1,data]
v = np.where(data%2==0,-1,data)
print v

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 0  2  4  6  8 10 12 14 16 18]
[[-1  1 -1  3 -1]
 [ 5 -1  7 -1  9]
 [-1 11 -1 13 -1]
 [15 -1 17 -1 19]]


In [ ]:
# Display all odd numbers in data
# Replace all even numbers in data with -1

In [103]:
data=np.arange(0,100,3)
print data
data_two = data[data%2==0] 
#print data_two
data_nine = data[data%9==0]
data_new = np.concatenate((data_two,data_nine),axis=0)
print data_new
# Display all values that are multiples of 2 or multiples of 9

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]
[ 0  6 12 18 24 30 36 42 48 54 60 66 72 78 84 90 96  0  9 18 27 36 45 54
 63 72 81 90 99]


In [102]:
def vool(a):
    data_two = [a%2==0 or a%9==0]
    print data_two
#vool(np.arange(0,100,2))
cvv = np.vectorize(vool)
cvv(np.arange(0,100,2))

[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]
[True]


array([None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None], dtype=object)

### Some additional snippets

In [4]:
data=np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype=np.float)
data

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [39]:
data[::-1]

array([[  6.,   7.,   8.,   9.,  10.],
       [  1.,   2.,   3.,   4.,   5.]])

In [40]:
data[0,::-1]

array([ 5.,  4.,  3.,  2.,  1.])

In [82]:
# Reverse both rows and columns of data
# OUTPUT
#array([[10,  9,  8,  7,  6],
#       [ 5,  4,  3,  2,  1]])
data[::-1,::-1]

array([[10.,  9.,  8.,  7.,  6.],
       [ 5.,  4.,  3.,  2.,  1.]])

In [7]:
data[0,0]=np.inf#to represent a finite number
data[-1,-2]=np.nan# to represnt a non number
data

array([[inf,  2.,  3.,  4., nan],
       [ 6.,  7.,  8., nan, nan]])

In [46]:
# Reshaping
reshaped=data.reshape((5,2))
reshaped

array([[ inf,   2.],
       [  3.,   4.],
       [  5.,   6.],
       [  7.,   8.],
       [  9.,  nan]])

In [47]:
flattened=data.flatten()
flattened

array([ inf,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  nan])

In [48]:
# Generating random numbers
np.random.rand(3,3)

array([[ 0.43071108,  0.22469197,  0.02480585],
       [ 0.81754419,  0.00923481,  0.26598393],
       [ 0.88085261,  0.00458565,  0.33238934]])

In [52]:
np.random.randint(0,10,(5,5))#row,col,#dddddddddddddddddd

array([[4, 8, 5, 9, 1],
       [2, 3, 9, 3, 2],
       [4, 3, 0, 2, 8],
       [2, 2, 7, 4, 2],
       [1, 7, 9, 8, 6]])

In [87]:
np.random.choice(['India','China','Australia','Canada','France'],(13,4))

array([['Australia', 'France', 'Canada', 'China'],
       ['China', 'China', 'Australia', 'Canada'],
       ['India', 'Australia', 'Australia', 'China'],
       ['India', 'India', 'Australia', 'Australia'],
       ['India', 'Canada', 'India', 'Canada'],
       ['China', 'France', 'Australia', 'France'],
       ['France', 'France', 'China', 'China'],
       ['China', 'France', 'China', 'China'],
       ['India', 'China', 'Australia', 'China'],
       ['Australia', 'Australia', 'France', 'Canada'],
       ['China', 'France', 'Canada', 'Canada'],
       ['Australia', 'France', 'India', 'Canada'],
       ['China', 'Australia', 'France', 'India']], dtype='|S9')

In [88]:
np.random.seed(10)
np.random.choice(['India','China','Australia','Canada','France'],(3,4))

array([['China', 'France', 'India', 'China'],
       ['Canada', 'France', 'China', 'India'],
       ['China', 'Australia', 'India', 'China']], dtype='|S9')

In [75]:
# Consider the set of students of class 10
names = ["Aaran", "Aaren", "Aarez", "Aarman", "Aaron", "Aaron-James", "Aarron", "Aaryan", "Aaryn", "Aayan", "Aazaan", "Abaan", "Abbas", "Abdallah", "Abdalroof", "Abdihakim", "Abdirahman", "Abdisalam", "Abdul", "Abdul-Aziz", "Abdulbasir", "Abdulkadir", "Abdulkarem"]
# The school is conducting a competition which requires 10 teams of 5 students each
competition=['Chess','Hockey',"Cricket","Volleyball","Football","Tennis","Shuttle",'Carrom',"Swimming","Long Jump"]
# Display the competition name and the students selected for the competition
e =np.random.choice(names,(10,5))
for name,competition in enumerate(competition):
    print competition +":"+ str(e[name])

Chess:['Aaryn' 'Aarron' 'Abdulkadir' 'Abdulkadir' 'Abdulkadir']
Hockey:['Abdulkadir' 'Abaan' 'Abdallah' 'Abdulbasir' 'Aaren']
Cricket:['Aaron-James' 'Abdisalam' 'Aayan' 'Aazaan' 'Abdisalam']
Volleyball:['Abaan' 'Aaryan' 'Abaan' 'Aarman' 'Abdulkadir']
Football:['Aayan' 'Abaan' 'Abdallah' 'Aarman' 'Abdul-Aziz']
Tennis:['Abbas' 'Aaryan' 'Aarron' 'Aaryan' 'Aaren']
Shuttle:['Aaron' 'Abdulbasir' 'Abdihakim' 'Aarman' 'Aayan']
Carrom:['Abdirahman' 'Abdallah' 'Aaren' 'Aazaan' 'Aazaan']
Swimming:['Abdihakim' 'Aaryan' 'Abdul' 'Abdulkarem' 'Abdisalam']
Long Jump:['Abdulkadir' 'Aarman' 'Aayan' 'Aazaan' 'Abdulkadir']


In [96]:
# Create an array of 100 elements using linspace
# Create all possible combination of arrays with it using reshape
# Eg. 1X100, 2X50, 4X25 ....
c = np.linspace(0,100)
#c = c.reshape((1,100))
ci = c.reshape((25,4))
ci

ValueError: cannot reshape array of size 50 into shape (25,4)

In [ ]:
# Create a 3X4 array (A) containing some even numbers,nan and inf
# What happens if we add a scalar to A?
# What happens if we add a normal array with A?
# What happens if we multiply a normal array with A?

### Vectorize

In [8]:
def calc(a):
    if a%2==0:
        return a**2
    else:
        return a-1

In [9]:
vals=np.array([1,2,3,4,5])

calc(vals[0])

0

In [10]:
calc(vals)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [11]:
v_calc=np.vectorize(calc)

v_calc(vals)

array([ 0,  4,  2, 16,  4])

In [ ]:
# Create a function that converts the numbers to its binary format
# Use vectorize to apply it on a numpy array

In [108]:
def binaryw(a):
    print bin(a)
    
c = np.array(np.arange(0,10,2))
print c
voooo = np.vectorize(binaryw)
voooo(c)

[0 2 4 6 8]
0b0
0b0
0b10
0b100
0b110
0b1000


array([None, None, None, None, None], dtype=object)

## Records - Using Heterogeneous Datatypes

In [66]:
rec=np.array([(1,(95.5,98),'Ram'),(2,(100,96.5),'Raj')],
             dtype=[('RollNo',np.int32),('Marks',np.float64,2),('Name',np.str,4)])

In [67]:
rec

array([(1, [  95.5,   98. ], 'Ram'), (2, [ 100. ,   96.5], 'Raj')], 
      dtype=[('RollNo', '<i4'), ('Marks', '<f8', (2,)), ('Name', 'S4')])

In [68]:
rec[0]

(1, [ 95.5,  98. ], 'Ram')

In [69]:
rec['Name']

array(['Ram', 'Raj'], 
      dtype='|S4')

In [70]:
rec[0]['Marks']

array([ 95.5,  98. ])

In [71]:
rec['Marks'][0]

array([ 95.5,  98. ])

In [111]:
schema=np.dtype([('year',np.float16),
                ('month',np.float16),
                ('day',np.float16),
                ('hour',np.float16),
                 ('minute',np.float16),
                 ('Temp',np.float16)])
np_data=np.loadtxt('C:\Users\Sureya\Desktop\data analiyics\done by me on class\dataset\weather1week.csv',dtype=schema,delimiter=';')
np_data

array([(2018., 9.,  9.,  0., 0., 22.64), (2018., 9.,  9.,  1., 0., 22.42),
       (2018., 9.,  9.,  2., 0., 22.3 ), (2018., 9.,  9.,  3., 0., 22.2 ),
       (2018., 9.,  9.,  4., 0., 22.14), (2018., 9.,  9.,  5., 0., 22.2 ),
       (2018., 9.,  9.,  6., 0., 23.39), (2018., 9.,  9.,  7., 0., 24.42),
       (2018., 9.,  9.,  8., 0., 24.7 ), (2018., 9.,  9.,  9., 0., 24.6 ),
       (2018., 9.,  9., 10., 0., 24.14), (2018., 9.,  9., 11., 0., 23.95),
       (2018., 9.,  9., 12., 0., 23.9 ), (2018., 9.,  9., 13., 0., 23.28),
       (2018., 9.,  9., 14., 0., 23.27), (2018., 9.,  9., 15., 0., 25.42),
       (2018., 9.,  9., 16., 0., 25.75), (2018., 9.,  9., 17., 0., 24.19),
       (2018., 9.,  9., 18., 0., 23.48), (2018., 9.,  9., 19., 0., 22.94),
       (2018., 9.,  9., 20., 0., 22.48), (2018., 9.,  9., 21., 0., 22.11),
       (2018., 9.,  9., 22., 0., 22.1 ), (2018., 9.,  9., 23., 0., 22.06),
       (2018., 9., 10.,  0., 0., 22.05), (2018., 9., 10.,  1., 0., 22.02),
       (2018., 9., 10.,  

In [113]:
np_data[1]

(2018., 9., 9., 1., 0., 22.42)

In [74]:
np_data['Temp']

array([ 22.640625,  22.421875,  22.296875,  22.203125,  22.140625,
        22.203125,  23.390625,  24.421875,  24.703125,  24.59375 ,
        24.140625,  23.953125,  23.90625 ,  23.28125 ,  23.265625,
        25.421875,  25.75    ,  24.1875  ,  23.484375,  22.9375  ,
        22.484375,  22.109375,  22.09375 ,  22.0625  ,  22.046875,
        22.015625,  22.      ,  22.      ,  22.015625,  22.046875,
        21.484375,  24.078125,  25.703125,  26.34375 ,  26.921875,
        25.265625,  24.6875  ,  25.484375,  24.046875,  23.953125,
        23.703125,  23.109375,  22.71875 ,  22.59375 ,  22.5     ,
        22.359375,  22.234375,  22.046875,  21.890625,  21.765625,
        21.6875  ,  21.65625 ,  21.625   ,  21.59375 ,  21.625   ,
        23.9375  ,  25.265625,  26.46875 ,  27.578125,  26.953125,
        26.453125,  25.5625  ,  24.609375,  24.109375,  23.765625,
        23.71875 ,  23.125   ,  22.953125,  22.859375,  22.703125,
        22.75    ,  22.765625,  22.609375,  22.453125,  22.484

In [76]:
np_data[0]['day']

9.0

In [77]:
np_data['Temp']=np_data['Temp']*(9/5)+32
np_data

array([( 2018.,  9.,   9.,   0.,  0.,  54.625  ),
       ( 2018.,  9.,   9.,   1.,  0.,  54.4375 ),
       ( 2018.,  9.,   9.,   2.,  0.,  54.3125 ),
       ( 2018.,  9.,   9.,   3.,  0.,  54.1875 ),
       ( 2018.,  9.,   9.,   4.,  0.,  54.125  ),
       ( 2018.,  9.,   9.,   5.,  0.,  54.1875 ),
       ( 2018.,  9.,   9.,   6.,  0.,  55.375  ),
       ( 2018.,  9.,   9.,   7.,  0.,  56.4375 ),
       ( 2018.,  9.,   9.,   8.,  0.,  56.6875 ),
       ( 2018.,  9.,   9.,   9.,  0.,  56.59375),
       ( 2018.,  9.,   9.,  10.,  0.,  56.125  ),
       ( 2018.,  9.,   9.,  11.,  0.,  55.9375 ),
       ( 2018.,  9.,   9.,  12.,  0.,  55.90625),
       ( 2018.,  9.,   9.,  13.,  0.,  55.28125),
       ( 2018.,  9.,   9.,  14.,  0.,  55.25   ),
       ( 2018.,  9.,   9.,  15.,  0.,  57.4375 ),
       ( 2018.,  9.,   9.,  16.,  0.,  57.75   ),
       ( 2018.,  9.,   9.,  17.,  0.,  56.1875 ),
       ( 2018.,  9.,   9.,  18.,  0.,  55.5    ),
       ( 2018.,  9.,   9.,  19.,  0.,  54.9375 ),


In [114]:
# Read the file weatherComp.csv
# Find which year was hotter 2017 or 2018
# Find which day was hotter 

schema=np.dtype([('year',np.float16),
                ('month',np.float16),
                ('day',np.float16),
                ('hour',np.float16),
                ('minute',np.float16),
                ('Temp17',np.float16),
                ('Temp18',np.float16)]) 
np_data=np.loadtxt('C:\Users\Sureya\Desktop\data analiyics\done by me on class\dataset\weatherComp.csv',dtype=schema,delimiter=';')
np_data
#print np_data[Temp17] + np_data[Temp18]

array([(2018., 9.,  9.,  0., 0., 22.64, 23.31),
       (2018., 9.,  9.,  1., 0., 22.42, 23.19),
       (2018., 9.,  9.,  2., 0., 22.3 , 22.62),
       (2018., 9.,  9.,  3., 0., 22.2 , 22.81),
       (2018., 9.,  9.,  4., 0., 22.14, 22.48),
       (2018., 9.,  9.,  5., 0., 22.2 , 22.55),
       (2018., 9.,  9.,  6., 0., 23.39, 23.38),
       (2018., 9.,  9.,  7., 0., 24.42, 24.42),
       (2018., 9.,  9.,  8., 0., 24.7 , 25.67),
       (2018., 9.,  9.,  9., 0., 24.6 , 25.3 ),
       (2018., 9.,  9., 10., 0., 24.14, 25.55),
       (2018., 9.,  9., 11., 0., 23.95, 25.7 ),
       (2018., 9.,  9., 12., 0., 23.9 , 27.69),
       (2018., 9.,  9., 13., 0., 23.28, 28.52),
       (2018., 9.,  9., 14., 0., 23.27, 27.2 ),
       (2018., 9.,  9., 15., 0., 25.42, 26.55),
       (2018., 9.,  9., 16., 0., 25.75, 26.25),
       (2018., 9.,  9., 17., 0., 24.19, 25.25),
       (2018., 9.,  9., 18., 0., 23.48, 24.27),
       (2018., 9.,  9., 19., 0., 22.94, 22.8 ),
       (2018., 9.,  9., 20., 0., 22.48, 

In [9]:
tinytuple = (123,'sureya')
tinytuple*2

(123, 'sureya', 123, 'sureya')

In [14]:
class tester:
    def __init__(self,id):
        self.id = str(id)
        id=""224""
        

SyntaxError: invalid syntax (<ipython-input-14-6c99cf4ec419>, line 4)

In [15]:
temp  =tester(12)

NameError: name 'tester' is not defined

In [16]:
print temp.id

NameError: name 'temp' is not defined

In [19]:
awards = ["mon",'sna','kun','pres','san','roch']
grad = ['mon','pres','roch']


In [20]:
[j for j in awards if j not in grad]

['sna', 'kun', 'san']

In [21]:
from nltk import ngrams

sentence = 'this is a foo bar sentences and i want to ngramize it'

n = 6
sixgrams = ngrams(sentence.split(), n)

for grams in sixgrams:
     print grams

('this', 'is', 'a', 'foo', 'bar', 'sentences')
('is', 'a', 'foo', 'bar', 'sentences', 'and')
('a', 'foo', 'bar', 'sentences', 'and', 'i')
('foo', 'bar', 'sentences', 'and', 'i', 'want')
('bar', 'sentences', 'and', 'i', 'want', 'to')
('sentences', 'and', 'i', 'want', 'to', 'ngramize')
('and', 'i', 'want', 'to', 'ngramize', 'it')
